### ISSUE TITLE
Implement protected route and JWT strategy guards

### ISSUE THREAD

**Issue by PascalM13** [SkyMatix44/tracking-backend#33]
https://docs.nestjs.com/security/authentication#implement-protected-route-and-jwt-strategy-guards)

**Comment by SkyMatix44** [comment]
Ah perrfekt, das stand auch noch auf meiner TODO-Liste 👍

Erstellst du auch direkt mehrere Guards für:
- Benutzer ist eingeloggt
- Benutzer ist Teilnehmer
- Benutzer ist Wissenschaftler
- Benutzer ist Admin

oder wollen wir die anderen Fälle nicht mit Guards lösen?

**Comment by PascalM13** [comment]
Ich hatte vor Guards für die unterschiedlichen Rollen zu erstellen

**Comment by PascalM13** [comment]
Beispiele zur Verwendung von den Guards sind im Controller für die University

**Comment by SkyMatix44** [comment]
@PascalM13  an `createUniversity` ist noch zwei mal Roles definiert, das ist falsch oder?

**Comment by PascalM13** [comment]
Hab ich gefixt
