### ISSUE TITLE
Endpunkt um derzeitigen Nutzer zu bekommen

### ISSUE THREAD

**Issue by PascalM13** [SkyMatix44/tracking-backend#36]
.../auth/me soll den derzeitigen Nutzer anhand des JWTs zurück geben

**Comment by PascalM13** [comment]
Wir brauchen beim Login/ Nach dem Login die ID und weitere Daten  des Nutzer wie z.B. den Namen etc.

**Comment by SkyMatix44** [comment]
Nutzerdaten werden direkt beim Login zurückgegeben
